### ISSUE TITLE
RTOS

### ISSUE THREAD

**Issue by waltergrillo** [qoriq-open-source/mc-binary#1]
Hi, sorry for the off topic, but I'm using nxp T1040D4RDB-PA and I'm looking for a RTOS for my board. I saw that nxp doesn't support any RTOS, but do you know of any unofficially supported OS?

**Comment by ting-liu** [comment]
Vxworks should support T1040 officially.

**Comment by IoanaCiornei** [comment]
Closed this issue since it's not related to the MC firmware.
